"""empty message

Revision ID: 537c4d24d33a
Revises: f0b1328c98c1
Create Date: 2026-01-08 17:24:27.222446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537c4d24d33a'
down_revision: Union[str, Sequence[str], None] = 'f0b1328c98c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.String(length=32), nullable=False))
    op.create_unique_constraint(None, 'employees', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
