"""empty message

Revision ID: 1f5340515fab
Revises: a9ba1687c621
Create Date: 2026-01-08 17:15:49.349095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5340515fab'
down_revision: Union[str, Sequence[str], None] = 'a9ba1687c621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_employee_id_key'), 'users', type_='unique')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_employee_id_key'), 'users', ['employee_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
