"""empty message

Revision ID: 7939c68e6f7e
Revises: 5eb2be4438ca
Create Date: 2026-01-07 21:50:05.462967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7939c68e6f7e'
down_revision: Union[str, Sequence[str], None] = '5eb2be4438ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'token_blacklist', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    # ### end Alembic commands ###
